name: Update README with latest issue comment

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the latest comment from the issue
        run: |
          ISSUE_NUMBER=1  
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          COMMENT=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments" | jq -r '.[0].body')
          echo "$COMMENT" > latest_comment.txt

      - name: Update README with the latest comment
        run: |
          COMMENT=$(cat latest_comment.txt)
          sed -i "/<!-- latest-comment -->/c\\
          $COMMENT
          " README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with the latest comment"
          git push