name: Update README with Latest Comment

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Latest Comment from Issue
        id: fetch-comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_comment=$(gh api repos/${{ github.repository }}/issues/1/comments --paginate --jq '.[-1].body')
          echo "$latest_comment" > latest_comment.txt

      - name: Insert Comment into README.md
        run: |
          latest_comment=$(cat latest_comment.txt)

          sed -i '/<!-- START-INSERT -->/,/<!-- END-INSERT -->/c\<!-- START-INSERT -->\n'"$latest_comment"'\n<!-- END-INSERT -->' README.md

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add README.md
          git commit -m "Update README with latest comment from Issue #1" || echo "No changes to commit"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}